/* 소아청소년과 추출항목 (2019-04-09) For MS-SQL(SQL Server 2012 이상)
   - 추출기준일(8개) : 진단일, 3개월, 6개월, 12개월, 24개월, 36개월, 48개월, 60개월
     : 6개월 까지는 전후 1.5개월(45일)을, 12개월 이후 시점부터는 전후 3개월 데이터를 기준으로 추출
     : Index date~45, 46~135, 136~227, 273~455, 638~820, 1003~1185, 1368~1550, 1733~1915
   - DAY_OF_BIRTH 필드 제외
   - 측정데이터 원천 다중화 (원천변경은 IN_PARAM.MEASUREMENT_SOURCE의 값만 변경하면 됨)
     : 키/체중/BMI : MEASUREMENT OR OBSERVATION
     : HbA1c : MEASUREMENT
   - COHORT_ID가 변경되면 IN_PARAM.COHORT_ID의 값을 변경
   - 당뇨병 종류(Type1, Type2) 추가
   - 신환환자만 선택
     1) 0, 3개월 사이의 HbA1c가 1이상 감소한 경우
     2) 0개월 근처(진단시점 INDEX_DATE ~ +3개월 이내) GAD Ab 검사가 최소 1번 있는 경우
     3) 0, 3개월 사이의 Weight가 증가한 경우
   - 해당 환자의 키/몸무게 데이터 추출 시 이상치 제거
     1) Weight : "환자별 0M Weight(Median) * 80%" ~ "환자별 마지막 시점의 Weight(Median) * 120%"
     2) Height : "환자별 0M Height(Median) * 97%" ~ "환자별 마지막 시점의 Height(Median) * 103%"

   - 2019-05-08 수정
     1) DM type 구분하는 CONDITION_DATA_DM에서 5년 기간 제거
     2) DKA는 진단&검사로 수정
     3) DKA 진단기준을 CONCEPT_ID에서 EXT_COND_SOURCE_VALUE_KCD (ICD10)로 변경
     4) 키, 몸무게, BMI와 HbA1c, GAD Ab 검사를 구분하였음
     5) SNU용 DKA 검사에서 코드 2개 수정

   - 2019-06-19 SNUH 버전 수정
     1) MEASUREMENT_SOURCE 테이블을 지정하였음 (모두 Measurement : 키,몸무게,BMI,HbA1c,GAD Ab)
     2) HbA1c concept_id 수정 : 3005673 --> 3007263
     3) 최종 Select 구문에서 Date field를 char로 type 변경
   
   - 2020-03-27 MS-SQL to Postgre SQL
     1) DATEADD >>> INTERVAL
	 2) DATEDIFF >>> DATE_PART
	 3) 날짜형식변환 : CONVERT >>> TO_CHAR
	 4) 자료형변환 : CONVERT >>> ::
	 5) ISNULL >>> COALESCE
   
   - 2020-03-31 MEDIAN 값 계산 수정
     1) 수정 : 267라인의 NORMAL_RANGE 테이블에서 이상치 제거용으로 생성하는 키, 몸무게에 대한 MEDIAN 계산쿼리 수정 (294행 추가)
	 2) 주석처리 : 309라인의 PRCS_DATA1 테이블 생성 제외 & 마지막 SELECT에서 PRCS_DATA1 관련 내용 제외
*/

WITH IN_PARAM AS (
     SELECT 4177340 AS CONCEPT_ID_HEIGHT /* 4177340(Height) */
          , 4099154 AS CONCEPT_ID_WEIGHT /* 4099154(Weight) */
          , 4245997 AS CONCEPT_ID_BMI    /* 4245997(BMI(EMR)) */
          , 3007263 AS CONCEPT_ID_HBA1C  /* SNUBH = 3005673(HbA1c) */
          , 3020148 AS CONCEPT_ID_GADAB  /* 3020148(GAD Ab 검사) */
--          , '99999' AS MEASUREMENT_SOURCE1 /* Height and Weight and BMI - '1':MEASUREMENT, '2':OBSERVATION */
--          , '99999' AS MEASUREMENT_SOURCE2 /* HbA1c and GAD Ab          - '1':MEASUREMENT, '2':OBSERVATION */
          , 99999 AS COHORT_ID
          , 0.97 AS HEIGHT_FR_RT /* HEIGHT 최저 가중치 */
          , 1.03 AS HEIGHT_TO_RT /* HEIGHT 최고 가중치 */
          , 0.8  AS WEIGHT_FR_RT /* WEIGHT 최저 가중치 */
          , 1.2  AS WEIGHT_TO_RT /* WEIGHT 최고 가중치 */
     )
   , COHORT_DATA AS (
     SELECT Z1.COHORT_ID
          , A1.SUBJECT_ID AS PERSON_ID
          , A1.COHORT_START_DATE
          --, DATEADD(DAY, -45, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE - INTERVAL '45 DAY') AS COHORT_START_DATE_00M_BF
          --, DATEADD(DAY,  -1, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE - INTERVAL '1 DAY') AS COHORT_START_DATE_00M
          --, DATEADD(DAY,  45, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '45 DAY') AS COHORT_START_DATE_00M_AF
          --, DATEADD(DAY,  46, A1.COHORT_START_DATE)
          , (A1.COHORT_START_DATE + INTERVAL '46 DAY') AS COHORT_START_DATE_03M_BF
		  --, DATEADD(month, 3, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '3 MONTH') AS COHORT_START_DATE_03M
          --, DATEADD(DAY, 135, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '135 DAY') AS COHORT_START_DATE_03M_AF
          --, DATEADD(DAY, 136, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '136 DAY') AS COHORT_START_DATE_06M_BF
          --, DATEADD(month, 6, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '6 MONTH') AS COHORT_START_DATE_06M
          --, DATEADD(DAY, 227, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '227 DAY') AS COHORT_START_DATE_06M_AF
          --, DATEADD(month, 9, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '9 MONTH') AS COHORT_START_DATE_12M_BF
          --, DATEADD(month,12, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '12 MONTH') AS COHORT_START_DATE_12M
          --, DATEADD(month,15, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '15 MONTH') AS COHORT_START_DATE_12M_AF
          --, DATEADD(month,21, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '21 MONTH') AS COHORT_START_DATE_24M_BF
          --, DATEADD(month,24, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '24 MONTH') AS COHORT_START_DATE_24M
          --, DATEADD(month,27, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '27 MONTH') AS COHORT_START_DATE_24M_AF
          --, DATEADD(month,33, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '33 MONTH') AS COHORT_START_DATE_36M_BF
          --, DATEADD(month,36, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '36 MONTH') AS COHORT_START_DATE_36M
          --, DATEADD(month,39, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '39 MONTH') AS COHORT_START_DATE_36M_AF
          --, DATEADD(month,45, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '45 MONTH') AS COHORT_START_DATE_48M_BF
          --, DATEADD(month,48, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '48 MONTH') AS COHORT_START_DATE_48M
          --, DATEADD(month,51, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '51 MONTH') AS COHORT_START_DATE_48M_AF
          --, DATEADD(month,57, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '57 MONTH') AS COHORT_START_DATE_60M_BF
          --, DATEADD(month,60, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '60 MONTH') AS COHORT_START_DATE_60M
          --, DATEADD(month,63, A1.COHORT_START_DATE)
		  , (A1.COHORT_START_DATE + INTERVAL '63 MONTH') AS COHORT_START_DATE_60M_AF
          , A1.COHORT_END_DATE
          , A2.GENDER_CONCEPT_ID
          , A2.YEAR_OF_BIRTH
          , A2.MONTH_OF_BIRTH
          , A2.DAY_OF_BIRTH
       FROM @RESULT_DB_SCHEMA.COHORT A1
          , @CDM_DB_SCHEMA.PERSON A2
          , IN_PARAM Z1
      WHERE A1.SUBJECT_ID = A2.PERSON_ID
        AND A1.COHORT_DEFINITION_ID = Z1.COHORT_ID
     )
   , CONDITION_DATA AS ( /* DKA여부, HHS여부 */
     SELECT B1.PERSON_ID
          , MAX(CASE WHEN B2.CONDITION_CONCEPT_ID =  443727 THEN 1 ELSE 0 END) AS DKA_YN
          , MAX(CASE WHEN B2.CONDITION_CONCEPT_ID = 4147719 THEN 1 ELSE 0 END) AS HHS_YN
       FROM COHORT_DATA B1
          , @CDM_DB_SCHEMA.CONDITION_OCCURRENCE B2
      WHERE B1.PERSON_ID = B2.PERSON_ID
        AND B2.CONDITION_START_DATE BETWEEN B1.COHORT_START_DATE AND B1.COHORT_END_DATE
        AND B2.CONDITION_CONCEPT_ID IN (443727, 4147719) /* 443727(DKA여부), 4147719(HHS여부) */
      GROUP BY B1.PERSON_ID
     )
   , CONDITION_DATA_NEW AS ( /* 2019-04-07 : (COHORT_START_DATE - 30 DAYS) ~ (COHORT_START_DATE + 7 DAYS) 진단기간 중 발생한 진단코드 사용 */
     SELECT B1.PERSON_ID
          --, MAX(DECODE(B2.CONDITION_CONCEPT_ID,  443727, 1, 0)) AS DKA_YN
          , MAX(CASE WHEN SUBSTRING(REPLACE(B2.EXT_COND_SOURCE_VALUE_KCD, '.', ''), 1, 4) IN ('E101','E111','E140','E141') THEN 1 ELSE 0 END) AS DKA_YN
          --, MAX(DECODE(B2.CONDITION_CONCEPT_ID, 4147719, 1, 0)) AS HHS_YN
          , MAX(CASE WHEN B2.CONDITION_CONCEPT_ID = 4147719 THEN 1 ELSE 0 END) AS HHS_YN
       FROM COHORT_DATA B1
          , @CDM_DB_SCHEMA.CONDITION_OCCURRENCE B2
      WHERE B1.PERSON_ID = B2.PERSON_ID
        --AND B2.CONDITION_START_DATE BETWEEN DATEADD(DAY, -30, B1.COHORT_START_DATE) AND DATEADD(DAY, 7, B1.COHORT_START_DATE)
        AND B2.CONDITION_START_DATE BETWEEN (B1.COHORT_START_DATE - INTERVAL '30 DAY') AND (B1.COHORT_START_DATE + INTERVAL '7 DAY')
		AND (B2.CONDITION_CONCEPT_ID IN (4147719)
         OR SUBSTRING(REPLACE(B2.EXT_COND_SOURCE_VALUE_KCD, '.', ''), 1, 4) IN ('E101','E111','E140','E141')) /* 443727(DKA여부), 4147719(HHS여부) */
      GROUP BY B1.PERSON_ID
     )
   , CONDITION_DATA_DM AS ( /* 2019-04-07 : COHORT_START_DATE ~ (COHORT_START_DATE + 5년) 기간 중 가장 마지막에 발생된 CONDITION을 기반으로 당뇨 TYPE 1과 2로 정의 */
                            /* 2019-05-08 : DM 여부에서 5년 기간 제외하고 전체 수진 기록 중으로 변경 */
     SELECT C1.PERSON_ID
          , CASE WHEN C1.LAST_CONDITION_CONCEPT_ID::INT IN (SELECT DESCENDANT_CONCEPT_ID FROM @VOCABULARY_DB_SCHEMA.CONCEPT_ANCESTOR WHERE ANCESTOR_CONCEPT_ID = 201254) THEN 1 ELSE 0 END AS DM1 /* 제1형 당뇨병 존재여부 */
          , CASE WHEN C1.LAST_CONDITION_CONCEPT_ID::INT IN (SELECT DESCENDANT_CONCEPT_ID FROM @VOCABULARY_DB_SCHEMA.CONCEPT_ANCESTOR WHERE ANCESTOR_CONCEPT_ID = 201826) THEN 1 ELSE 0 END AS DM2 /* 제2형 당뇨병 존재여부 */
       FROM (SELECT B1.PERSON_ID
                  --, SUBSTRING(MAX(CONCAT(CONVERT(VARCHAR(8), B2.CONDITION_START_DATE, 112), B2.CONDITION_CONCEPT_ID)), 9, 20) AS LAST_CONDITION_CONCEPT_ID /* 가장 마지막 진단의 CONDITION_CONCEPT_ID */
				  , SUBSTRING(MAX(CONCAT(TO_CHAR(B2.condition_start_date, 'YYYYMMDD'), B2.CONDITION_CONCEPT_ID)), 9, 20) AS LAST_CONDITION_CONCEPT_ID /* 가장 마지막 진단의 CONDITION_CONCEPT_ID */
               FROM COHORT_DATA B1
                  , @CDM_DB_SCHEMA.CONDITION_OCCURRENCE B2
              WHERE B1.PERSON_ID = B2.PERSON_ID
                --AND B2.CONDITION_START_DATE BETWEEN B1.COHORT_START_DATE AND B1.COHORT_START_DATE_60M
                AND B2.CONDITION_CONCEPT_ID IN (SELECT DESCENDANT_CONCEPT_ID
                                                  FROM @VOCABULARY_DB_SCHEMA.CONCEPT_ANCESTOR
                                                 WHERE ANCESTOR_CONCEPT_ID IN (201254, 201826) /* 201254(제1형 당뇨병 상위 CONCEPT_ID), 201826(제2형 당뇨병 상위 CONCEPT_ID) */
                                               )
              GROUP BY B1.PERSON_ID
            ) C1
     )
   , MEASUREMENT_DATA AS (
     SELECT C1.PERSON_ID
          , C2.MEASUREMENT_CONCEPT_ID
          , C2.MEASUREMENT_DATE
          , C2.VALUE_AS_NUMBER
          , 'MEASUREMENT' AS MEASUREMENT_SOURCE
       FROM COHORT_DATA C1
          , @CDM_DB_SCHEMA.MEASUREMENT C2
          , IN_PARAM Z1
      WHERE C1.PERSON_ID = C2.PERSON_ID
--        AND Z1.MEASUREMENT_SOURCE1 = '1'
    --AND (Z1.MEASUREMENT_SOURCE1 = '1' OR (Z1.MEASUREMENT_SOURCE1 = '2' AND C2.MEASUREMENT_CONCEPT_ID IN (Z1.CONCEPT_ID_HBA1C)))
        AND C2.MEASUREMENT_CONCEPT_ID IN (Z1.CONCEPT_ID_HEIGHT, Z1.CONCEPT_ID_WEIGHT, Z1.CONCEPT_ID_BMI, Z1.CONCEPT_ID_HBA1C, Z1.CONCEPT_ID_GADAB)
/*      UNION ALL
     SELECT C1.PERSON_ID
          , C2.OBSERVATION_CONCEPT_ID AS MEASUREMENT_CONCEPT_ID
          , C2.OBSERVATION_DATE AS MEASUREMENT_DATE
          , C2.VALUE_AS_NUMBER
          , 'OBSERVATION' AS MEASUREMENT_SOURCE
       FROM COHORT_DATA C1
          , @CDM_DB_SCHEMA.OBSERVATION C2
          , IN_PARAM Z1
      WHERE Z1.MEASUREMENT_SOURCE1 = '2'
        AND C1.PERSON_ID = C2.PERSON_ID
        AND C2.OBSERVATION_CONCEPT_ID IN (Z1.CONCEPT_ID_HEIGHT, Z1.CONCEPT_ID_WEIGHT, Z1.CONCEPT_ID_BMI, Z1.CONCEPT_ID_GADAB)
     )
   , MEASUREMENT_DATA2 AS (
     SELECT C1.PERSON_ID
          , C2.MEASUREMENT_CONCEPT_ID
          , C2.MEASUREMENT_DATE
          , C2.VALUE_AS_NUMBER
          , 'MEASUREMENT' AS MEASUREMENT_SOURCE
       FROM COHORT_DATA C1
          , @CDM_DB_SCHEMA.MEASUREMENT C2
          , IN_PARAM Z1
      WHERE C1.PERSON_ID = C2.PERSON_ID
        AND Z1.MEASUREMENT_SOURCE2 = '1'
    --AND (Z1.MEASUREMENT_SOURCE2 = '1' OR (Z1.MEASUREMENT_SOURCE2 = '2' AND C2.MEASUREMENT_CONCEPT_ID IN (Z1.CONCEPT_ID_HBA1C)))
        AND C2.MEASUREMENT_CONCEPT_ID IN (Z1.CONCEPT_ID_HEIGHT, Z1.CONCEPT_ID_WEIGHT, Z1.CONCEPT_ID_BMI, Z1.CONCEPT_ID_HBA1C, Z1.CONCEPT_ID_GADAB)
      UNION ALL
     SELECT C1.PERSON_ID
          , C2.OBSERVATION_CONCEPT_ID AS MEASUREMENT_CONCEPT_ID
          , C2.OBSERVATION_DATE AS MEASUREMENT_DATE
          , C2.VALUE_AS_NUMBER
          , 'OBSERVATION' AS MEASUREMENT_SOURCE
       FROM COHORT_DATA C1
          , @CDM_DB_SCHEMA.OBSERVATION C2
          , IN_PARAM Z1
      WHERE Z1.MEASUREMENT_SOURCE2 = '2'
        AND C1.PERSON_ID = C2.PERSON_ID
        AND C2.OBSERVATION_CONCEPT_ID IN (Z1.CONCEPT_ID_HEIGHT, Z1.CONCEPT_ID_WEIGHT, Z1.CONCEPT_ID_BMI, Z1.CONCEPT_ID_GADAB)
     )
   , MEASUREMENT_DATA AS (
     SELECT *
       FROM MEASUREMENT_DATA1
      UNION ALL
     SELECT *
       FROM MEASUREMENT_DATA2
*/     )
   , MEASUREMENT_DKA_BASE_DATA AS ( -- INDEX_DATE 기준 3개월 이내 발생한 검사결과들로 비교 (20190207, KS)
     SELECT A1.*
       FROM @CDM_DB_SCHEMA.MEASUREMENT A1
      INNER JOIN COHORT_DATA B1 ON A1.PERSON_ID = B1.PERSON_ID
      --WHERE A1.MEASUREMENT_DATE BETWEEN DATEADD(DAY, -90, B1.COHORT_START_DATE) AND B1.COHORT_START_DATE
	  WHERE A1.MEASUREMENT_DATE BETWEEN (B1.COHORT_START_DATE - INTERVAL '90 DAY') AND B1.COHORT_START_DATE
     )
   , MEASUREMENT_DKA_DATA AS (
     SELECT D1.PERSON_ID
          , CASE WHEN COUNT(D2.MEASUREMENT_CONCEPT_ID) =  0 THEN 'N' ELSE 'Y' END AS DKA_YN
       FROM COHORT_DATA D1
      INNER JOIN MEASUREMENT_DKA_BASE_DATA D2 ON D1.PERSON_ID = D2.PERSON_ID
      INNER JOIN MEASUREMENT_DKA_BASE_DATA D3 ON D2.PERSON_ID = D3.PERSON_ID
      WHERE ((D2.MEASUREMENT_CONCEPT_ID IN ('3019977', '3012544')            AND D2.VALUE_AS_NUMBER < 7.3) /* pH < 7.3 */
          OR (D2.MEASUREMENT_CONCEPT_ID IN ('3008152', '3027273', '3015235') AND D2.VALUE_AS_NUMBER < 15)  /* HCO3- < 15 */
            )
        AND ((D3.MEASUREMENT_CONCEPT_ID IN ('3035350')  AND D3.VALUE_AS_CONCEPT_ID IN (4126673,4125547,4126674)) /* urinalysis 에서 ketone 양성(2+이상) : 3028893 에서 바꿈*/
          OR (D3.MEASUREMENT_CONCEPT_ID IN ('3046325')  AND D3.VALUE_AS_NUMBER >= 180)                           /* 혈액 검사에서 ketone 양성(Beta hydroxybutyric acid) : 3003985 에서 바꿈 */
          OR (D3.MEASUREMENT_CONCEPT_ID IN ('40769111') AND D3.VALUE_AS_NUMBER >= 3)                             /* 혈액 검사에서 ketone 양성(Ketone (Beta hydroxybutyate)) */
          -- 20190208 회의에서 아래 결과는 제외해서 분석하기로 논의
          --OR (D3.MEASUREMENT_CONCEPT_ID IN ('3035132')  AND VALUE_AS_CONCEPT_ID IN (4123508,4126673,4125547,4126674)) /* 혈액 검사에서 ketone 양성(Ketone bodies (em) 1+ 이상) */
            )
      GROUP BY D1.PERSON_ID
     )
   , MEASUREMENT_DKA_DATA_NEW AS ( /* 2019-04-07 : (COHORT_START_DATE - 30 DAYS) ~ (COHORT_START_DATE + 7 DAYS) 기간 중 COHORT_START_DATE에 가장 가까운 검사결과 값 사용 */
     SELECT F1.PERSON_ID
          , MAX(CASE WHEN  F1.MEASUREMENT_CONCEPT_ID IN (3019977, 3012544)          AND F1.VALUE_AS_NUMBER < 7.3 THEN 'Y' END) AS DKA_TEST1
          , MAX(CASE WHEN  F1.MEASUREMENT_CONCEPT_ID IN (3008152, 3027273, 3015235) AND F1.VALUE_AS_NUMBER < 15  THEN 'Y' END) AS DKA_TEST2
          , MAX(CASE WHEN  F1.MEASUREMENT_CONCEPT_ID IN (3035350) AND F1.VALUE_AS_CONCEPT_ID IN (4126673, 4125547, 4126674) THEN 'Y' END) AS DKA_TEST3
          , MAX(CASE WHEN (F1.MEASUREMENT_CONCEPT_ID IN (3046325) AND F1.VALUE_AS_NUMBER >= 180) OR (F1.MEASUREMENT_CONCEPT_ID IN (40769111) AND F1.VALUE_AS_NUMBER >= 3) THEN 'Y' END) AS DKA_TEST4
       FROM (SELECT E2.PERSON_ID, E2.MEASUREMENT_CONCEPT_ID, E2.VALUE_AS_NUMBER, E2.VALUE_AS_CONCEPT_ID, E2.MEASUREMENT_DATE, E1.COHORT_START_DATE
                  --, ROW_NUMBER() OVER (PARTITION BY E2.PERSON_ID, E2.MEASUREMENT_CONCEPT_ID ORDER BY ABS(DATEDIFF(day, E1.COHORT_START_DATE, E2.MEASUREMENT_DATE))) AS RN
				  , ROW_NUMBER() OVER (PARTITION BY E2.PERSON_ID, E2.MEASUREMENT_CONCEPT_ID ORDER BY ABS(DATE_PART('day', E2.MEASUREMENT_DATE::TIMESTAMP - E1.COHORT_START_DATE::TIMESTAMP))) AS RN
               FROM COHORT_DATA E1
                  , @CDM_DB_SCHEMA.MEASUREMENT E2
              WHERE E1.PERSON_ID = E2.PERSON_ID
                --AND E2.MEASUREMENT_DATE BETWEEN DATEADD(DAY, -30, E1.COHORT_START_DATE) AND DATEADD(DAY, 7, E1.COHORT_START_DATE)
                AND E2.MEASUREMENT_DATE BETWEEN (E1.COHORT_START_DATE - INTERVAL '30 DAY') AND (E1.COHORT_START_DATE + INTERVAL '7 DAY')
				AND E2.MEASUREMENT_CONCEPT_ID IN (3019977, 3012544, 3008152, 3027273, 3015235, 3035350, 3046325, 40769111)
            ) F1
      WHERE F1.RN = 1
      GROUP BY F1.PERSON_ID
     )
   , NORMAL_RANGE AS ( /* 해당 환자의 키/몸무게 데이터 추출 시 이상치 제거용 */
     SELECT T1.PERSON_ID
		  , ROUND((COALESCE(T1.HEIGHT_00M_MED,0) * Z1.HEIGHT_FR_RT)::NUMERIC, 2) AS HEIGHT_FR
		  , ROUND((COALESCE(COALESCE(T1.HEIGHT_60M_MED, T1.HEIGHT_48M_MED, T1.HEIGHT_36M_MED, T1.HEIGHT_24M_MED, T1.HEIGHT_12M_MED, T1.HEIGHT_06M_MED, T1.HEIGHT_03M_MED, T1.HEIGHT_00M_MED),0) * Z1.HEIGHT_TO_RT)::NUMERIC, 2) AS HEIGHT_TO
		  , ROUND((COALESCE(T1.WEIGHT_00M_MED,0) * Z1.WEIGHT_FR_RT)::NUMERIC, 2) AS WEIGHT_FR
		  , ROUND((COALESCE(COALESCE(T1.WEIGHT_60M_MED, T1.WEIGHT_48M_MED, T1.WEIGHT_36M_MED, T1.WEIGHT_24M_MED, T1.WEIGHT_12M_MED, T1.WEIGHT_06M_MED, T1.WEIGHT_03M_MED, T1.WEIGHT_00M_MED),0) * Z1.WEIGHT_TO_RT)::NUMERIC, 2) AS WEIGHT_TO
       FROM (SELECT DISTINCT S1.PERSON_ID
                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_00M_BF AND S1.COHORT_START_DATE_00M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS HEIGHT_00M_MED
                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_03M_BF AND S1.COHORT_START_DATE_03M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS HEIGHT_03M_MED
                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_06M_BF AND S1.COHORT_START_DATE_06M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS HEIGHT_06M_MED
                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_12M_BF AND S1.COHORT_START_DATE_12M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS HEIGHT_12M_MED
                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_24M_BF AND S1.COHORT_START_DATE_24M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS HEIGHT_24M_MED
                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_36M_BF AND S1.COHORT_START_DATE_36M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS HEIGHT_36M_MED
                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_48M_BF AND S1.COHORT_START_DATE_48M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS HEIGHT_48M_MED
                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_60M_BF AND S1.COHORT_START_DATE_60M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS HEIGHT_60M_MED

                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_00M_BF AND S1.COHORT_START_DATE_00M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS WEIGHT_00M_MED
                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_03M_BF AND S1.COHORT_START_DATE_03M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS WEIGHT_03M_MED
                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_06M_BF AND S1.COHORT_START_DATE_06M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS WEIGHT_06M_MED
                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_12M_BF AND S1.COHORT_START_DATE_12M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS WEIGHT_12M_MED
                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_24M_BF AND S1.COHORT_START_DATE_24M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS WEIGHT_24M_MED
                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_36M_BF AND S1.COHORT_START_DATE_36M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS WEIGHT_36M_MED
                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_48M_BF AND S1.COHORT_START_DATE_48M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS WEIGHT_48M_MED
                  , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN S2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND S2.MEASUREMENT_DATE BETWEEN S1.COHORT_START_DATE_60M_BF AND S1.COHORT_START_DATE_60M_AF THEN S2.VALUE_AS_NUMBER END)) /* OVER(PARTITION BY S1.PERSON_ID) */ AS WEIGHT_60M_MED
               FROM COHORT_DATA S1
               LEFT OUTER JOIN MEASUREMENT_DATA S2 ON S1.PERSON_ID = S2.PERSON_ID
              CROSS JOIN IN_PARAM Z1
			  GROUP BY S1.PERSON_ID /* KS 추가 : 2020-03-31 / PERCENTILE_CONT 계산시 PARTITION BY 제외하면서 GROUP BY 추가 */
            ) T1
          , IN_PARAM Z1
     )
   , NORMAL_MEASUREMENT AS ( /* 해당 환자의 키/몸무게 이상치가 제거된 MEASUREMENT */
     SELECT K1.PERSON_ID, K1.MEASUREMENT_CONCEPT_ID, K1.MEASUREMENT_DATE, K1.VALUE_AS_NUMBER
       FROM MEASUREMENT_DATA K1
          , NORMAL_RANGE K2 /* 해당 환자의 키/몸무게 데이터 추출 시 이상치 제거 */
          , IN_PARAM Z1
      WHERE K1.PERSON_ID = K2.PERSON_ID
        AND ((K1.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND K1.VALUE_AS_NUMBER BETWEEN K2.HEIGHT_FR AND K2.HEIGHT_TO)
          OR (K1.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND K1.VALUE_AS_NUMBER BETWEEN K2.WEIGHT_FR AND K2.WEIGHT_TO)
          OR (K1.MEASUREMENT_CONCEPT_ID IN (Z1.CONCEPT_ID_BMI, Z1.CONCEPT_ID_HBA1C, Z1.CONCEPT_ID_GADAB))
            )
     )
--   , PRCS_DATA1 AS ( /* 중앙값(MEDIAN) 데이터 */
--     SELECT DISTINCT T1.PERSON_ID
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HEIGHT_00M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HEIGHT_03M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HEIGHT_06M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HEIGHT_12M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HEIGHT_24M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HEIGHT_36M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HEIGHT_48M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HEIGHT_60M_MED

--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS WEIGHT_00M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS WEIGHT_03M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS WEIGHT_06M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS WEIGHT_12M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS WEIGHT_24M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS WEIGHT_36M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS WEIGHT_48M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS WEIGHT_60M_MED

--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS BMI_00M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS BMI_03M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS BMI_06M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS BMI_12M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS BMI_24M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS BMI_36M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS BMI_48M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS BMI_60M_MED

--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HBA1C_00M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HBA1C_03M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HBA1C_06M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HBA1C_12M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HBA1C_24M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HBA1C_36M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HBA1C_48M_MED
--          , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END)) OVER(PARTITION BY T1.PERSON_ID) AS HBA1C_60M_MED
--       FROM COHORT_DATA T1
--          , NORMAL_MEASUREMENT T2
--          , IN_PARAM Z1
--      WHERE T1.PERSON_ID = T2.PERSON_ID
--        --AND EXISTS (SELECT 1 /* 신환환자 한정 : 0개월 근처(진단시점 INDEX_DATE ~ +3개월 이내) GAD Ab 검사가 최소 1번 있는 경우 */
--        --              FROM MEASUREMENT_DATA S1
--        --             WHERE S1.PERSON_ID = T1.PERSON_ID
--        --               AND S1.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_GADAB
--        --               AND S1.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE AND T1.COHORT_START_DATE_03M
--        --           )
--     )
   , PRCS_DATA2 AS ( /* 중앙값(MEDIAN) 외 데이터 */
     SELECT T1.PERSON_ID
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN CONCAT((CASE WHEN SIGN(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_00M)) = -1 THEN 1 ELSE 0 END), RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_00M))), 3), T2.VALUE_AS_NUMBER) END), 5, 100)::NUMERIC AS HEIGHT_00M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_00M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_00M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HEIGHT_00M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_03M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS HEIGHT_03M          
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_03M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_03M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HEIGHT_03M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_06M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS HEIGHT_06M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_06M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_06M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HEIGHT_06M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_12M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS HEIGHT_12M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_12M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_12M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HEIGHT_12M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_24M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS HEIGHT_24M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_24M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_24M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HEIGHT_24M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_36M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS HEIGHT_36M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_36M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_36M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HEIGHT_36M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_48M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS HEIGHT_48M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_48M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_48M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HEIGHT_48M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_60M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS HEIGHT_60M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_60M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END) AS HEIGHT_60M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HEIGHT_60M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN CONCAT((CASE WHEN SIGN(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_00M)) = -1 THEN 1 ELSE 0 END), RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_00M))), 3), T2.VALUE_AS_NUMBER) END), 5, 100)::NUMERIC AS WEIGHT_00M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_00M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_00M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS WEIGHT_00M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_03M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS WEIGHT_03M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_03M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_03M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS WEIGHT_03M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_06M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS WEIGHT_06M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_06M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_06M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS WEIGHT_06M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_12M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS WEIGHT_12M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_12M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_12M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS WEIGHT_12M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_24M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS WEIGHT_24M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_24M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_24M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS WEIGHT_24M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_36M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS WEIGHT_36M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_36M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_36M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS WEIGHT_36M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_48M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS WEIGHT_48M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_48M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_48M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS WEIGHT_48M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_60M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS WEIGHT_60M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_60M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END) AS WEIGHT_60M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_WEIGHT AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS WEIGHT_60M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN CONCAT((CASE WHEN SIGN(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_00M)) = -1 THEN 1 ELSE 0 END), RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_00M))), 3), T2.VALUE_AS_NUMBER) END), 5, 100)::NUMERIC AS BMI_00M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_00M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_00M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS BMI_00M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_03M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS BMI_03M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_03M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_03M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS BMI_03M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_06M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS BMI_06M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_06M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_06M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS BMI_06M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_12M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS BMI_12M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_12M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_12M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS BMI_12M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_24M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS BMI_24M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_24M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_24M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS BMI_24M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_36M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS BMI_36M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_36M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_36M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS BMI_36M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_48M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS BMI_48M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_48M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_48M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS BMI_48M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_60M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS BMI_60M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_60M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END) AS BMI_60M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_BMI AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS BMI_60M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN CONCAT((CASE WHEN SIGN(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_00M)) = -1 THEN 1 ELSE 0 END), RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_00M))), 3), T2.VALUE_AS_NUMBER) END), 5, 100)::NUMERIC AS HBA1C_00M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_00M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_00M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_00M_BF AND T1.COHORT_START_DATE_00M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HBA1C_00M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_03M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS HBA1C_03M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_03M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_03M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_03M_BF AND T1.COHORT_START_DATE_03M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HBA1C_03M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_06M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS HBA1C_06M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_06M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_06M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_06M_BF AND T1.COHORT_START_DATE_06M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HBA1C_06M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_12M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS HBA1C_12M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_12M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_12M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_12M_BF AND T1.COHORT_START_DATE_12M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HBA1C_12M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_24M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS HBA1C_24M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_24M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_24M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_24M_BF AND T1.COHORT_START_DATE_24M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HBA1C_24M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_36M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS HBA1C_36M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_36M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_36M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_36M_BF AND T1.COHORT_START_DATE_36M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HBA1C_36M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_48M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS HBA1C_48M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_48M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_48M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_48M_BF AND T1.COHORT_START_DATE_48M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HBA1C_48M_AVG
          , SUBSTRING(MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN CONCAT(RIGHT(CONCAT('000', ABS(DATE_PART('DAY', T2.MEASUREMENT_DATE - T1.COHORT_START_DATE_60M))), 3), T2.VALUE_AS_NUMBER) END), 4, 100)::NUMERIC AS HBA1C_60M
          ,       MIN(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_60M_MIN
          ,       MAX(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END) AS HBA1C_60M_MAX
          , ROUND(AVG(CASE WHEN T2.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_HBA1C AND T2.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE_60M_BF AND T1.COHORT_START_DATE_60M_AF THEN T2.VALUE_AS_NUMBER END)::NUMERIC, 2) AS HBA1C_60M_AVG
       FROM COHORT_DATA T1
          , NORMAL_MEASUREMENT T2
          , IN_PARAM Z1
      WHERE T1.PERSON_ID = T2.PERSON_ID
--        AND EXISTS (SELECT 1 /* 신환환자 한정 : 0개월 근처(진단시점 INDEX_DATE ~ +3개월 이내) GAD Ab 검사가 최소 1번 있는 경우 */
--                      FROM MEASUREMENT_DATA S1
--                     WHERE S1.PERSON_ID = T1.PERSON_ID
--                       AND S1.MEASUREMENT_CONCEPT_ID = Z1.CONCEPT_ID_GADAB
--                       AND S1.MEASUREMENT_DATE BETWEEN T1.COHORT_START_DATE AND T1.COHORT_START_DATE_03M
--                   )
      GROUP BY T1.PERSON_ID
     )
--SELECT COUNT(*), COUNT(DISTINCT PERSON_ID) FROM (
SELECT M1.COHORT_ID, M1.PERSON_ID, M1.GENDER_CONCEPT_ID, M1.YEAR_OF_BIRTH, M1.MONTH_OF_BIRTH /*, M1.DAY_OF_BIRTH */
     --, M1.COHORT_START_DATE, M1.COHORT_END_DATE
     , TO_CHAR(M1.COHORT_START_DATE, 'YYYY-MM-DD') AS COHORT_START_DATE, TO_CHAR(M1.COHORT_END_DATE, 'YYYY-MM-DD') AS COHORT_END_DATE
     , COALESCE(M2.DKA_YN, 0) AS DKA_YN_DX -- DKA여부(진단기준)
     , COALESCE(M4.DKA_YN, 0) AS DKA_YN    -- DKA여부(검사기준)
     , COALESCE(M7.DKA_YN, 0) AS DKA_YN_DX_NEW -- DKA여부(진단기준)
     , CASE WHEN (M8.DKA_TEST1 = 'Y' OR M8.DKA_TEST2 = 'Y') AND (M8.DKA_TEST3 = 'Y' OR M8.DKA_TEST4 = 'Y') THEN 1 ELSE 0 END AS DKA_YN_TEST_NEW /* DKA여부(검사기준) */
     , CASE WHEN M7.DKA_YN = 1 OR ((M8.DKA_TEST1 = 'Y' OR M8.DKA_TEST2 = 'Y') AND (M8.DKA_TEST3 = 'Y' OR M8.DKA_TEST4 = 'Y')) THEN 1 ELSE 0 END AS DKA_YN_NEW /* DKA여부 (2019-04-07 : 진단 Y or 검사 Y 이면 DKA로 정의) */
     , COALESCE(M2.HHS_YN, 0) AS HHS_YN
     , CASE WHEN M3.DM1 = 1 AND M3.DM2 = 0 THEN 1 /* 1형 당뇨병만 존재할 경우 1 */
            WHEN M3.DM2 = 1 AND M3.DM1 = 0 THEN 2 /* 2형 당뇨병만 존재할 경우 2 */
            ELSE 0 /* 1형과 2형 당뇨병이 모두 없거나, 모두 있으면 0 */
       END AS DM

     , M6.HEIGHT_00M, M6.HEIGHT_00M_MIN, M6.HEIGHT_00M_MAX, M6.HEIGHT_00M_AVG --, M5.HEIGHT_00M_MED
     , M6.HEIGHT_03M, M6.HEIGHT_03M_MIN, M6.HEIGHT_03M_MAX, M6.HEIGHT_03M_AVG --, M5.HEIGHT_03M_MED
     , M6.HEIGHT_06M, M6.HEIGHT_06M_MIN, M6.HEIGHT_06M_MAX, M6.HEIGHT_06M_AVG --, M5.HEIGHT_06M_MED
     , M6.HEIGHT_12M, M6.HEIGHT_12M_MIN, M6.HEIGHT_12M_MAX, M6.HEIGHT_12M_AVG --, M5.HEIGHT_12M_MED
     , M6.HEIGHT_24M, M6.HEIGHT_24M_MIN, M6.HEIGHT_24M_MAX, M6.HEIGHT_24M_AVG --, M5.HEIGHT_24M_MED
     , M6.HEIGHT_36M, M6.HEIGHT_36M_MIN, M6.HEIGHT_36M_MAX, M6.HEIGHT_36M_AVG --, M5.HEIGHT_36M_MED
     , M6.HEIGHT_48M, M6.HEIGHT_48M_MIN, M6.HEIGHT_48M_MAX, M6.HEIGHT_48M_AVG --, M5.HEIGHT_48M_MED
     , M6.HEIGHT_60M, M6.HEIGHT_60M_MIN, M6.HEIGHT_60M_MAX, M6.HEIGHT_60M_AVG --, M5.HEIGHT_60M_MED

     , M6.WEIGHT_00M, M6.WEIGHT_00M_MIN, M6.WEIGHT_00M_MAX, M6.WEIGHT_00M_AVG --, M5.WEIGHT_00M_MED
     , M6.WEIGHT_03M, M6.WEIGHT_03M_MIN, M6.WEIGHT_03M_MAX, M6.WEIGHT_03M_AVG --, M5.WEIGHT_03M_MED
     , M6.WEIGHT_06M, M6.WEIGHT_06M_MIN, M6.WEIGHT_06M_MAX, M6.WEIGHT_06M_AVG --, M5.WEIGHT_06M_MED
     , M6.WEIGHT_12M, M6.WEIGHT_12M_MIN, M6.WEIGHT_12M_MAX, M6.WEIGHT_12M_AVG --, M5.WEIGHT_12M_MED
     , M6.WEIGHT_24M, M6.WEIGHT_24M_MIN, M6.WEIGHT_24M_MAX, M6.WEIGHT_24M_AVG --, M5.WEIGHT_24M_MED
     , M6.WEIGHT_36M, M6.WEIGHT_36M_MIN, M6.WEIGHT_36M_MAX, M6.WEIGHT_36M_AVG --, M5.WEIGHT_36M_MED
     , M6.WEIGHT_48M, M6.WEIGHT_48M_MIN, M6.WEIGHT_48M_MAX, M6.WEIGHT_48M_AVG --, M5.WEIGHT_48M_MED
     , M6.WEIGHT_60M, M6.WEIGHT_60M_MIN, M6.WEIGHT_60M_MAX, M6.WEIGHT_60M_AVG --, M5.WEIGHT_60M_MED

     , M6.BMI_00M, M6.BMI_00M_MIN, M6.BMI_00M_MAX, M6.BMI_00M_AVG --, M5.BMI_00M_MED
     , M6.BMI_03M, M6.BMI_03M_MIN, M6.BMI_03M_MAX, M6.BMI_03M_AVG --, M5.BMI_03M_MED
     , M6.BMI_06M, M6.BMI_06M_MIN, M6.BMI_06M_MAX, M6.BMI_06M_AVG --, M5.BMI_06M_MED
     , M6.BMI_12M, M6.BMI_12M_MIN, M6.BMI_12M_MAX, M6.BMI_12M_AVG --, M5.BMI_12M_MED
     , M6.BMI_24M, M6.BMI_24M_MIN, M6.BMI_24M_MAX, M6.BMI_24M_AVG --, M5.BMI_24M_MED
     , M6.BMI_36M, M6.BMI_36M_MIN, M6.BMI_36M_MAX, M6.BMI_36M_AVG --, M5.BMI_36M_MED
     , M6.BMI_48M, M6.BMI_48M_MIN, M6.BMI_48M_MAX, M6.BMI_48M_AVG --, M5.BMI_48M_MED
     , M6.BMI_60M, M6.BMI_60M_MIN, M6.BMI_60M_MAX, M6.BMI_60M_AVG --, M5.BMI_60M_MED

     , M6.HBA1C_00M, M6.HBA1C_00M_MIN, M6.HBA1C_00M_MAX, M6.HBA1C_00M_AVG --, M5.HBA1C_00M_MED
     , M6.HBA1C_03M, M6.HBA1C_03M_MIN, M6.HBA1C_03M_MAX, M6.HBA1C_03M_AVG --, M5.HBA1C_03M_MED
     , M6.HBA1C_06M, M6.HBA1C_06M_MIN, M6.HBA1C_06M_MAX, M6.HBA1C_06M_AVG --, M5.HBA1C_06M_MED
     , M6.HBA1C_12M, M6.HBA1C_12M_MIN, M6.HBA1C_12M_MAX, M6.HBA1C_12M_AVG --, M5.HBA1C_12M_MED
     , M6.HBA1C_24M, M6.HBA1C_24M_MIN, M6.HBA1C_24M_MAX, M6.HBA1C_24M_AVG --, M5.HBA1C_24M_MED
     , M6.HBA1C_36M, M6.HBA1C_36M_MIN, M6.HBA1C_36M_MAX, M6.HBA1C_36M_AVG --, M5.HBA1C_36M_MED
     , M6.HBA1C_48M, M6.HBA1C_48M_MIN, M6.HBA1C_48M_MAX, M6.HBA1C_48M_AVG --, M5.HBA1C_48M_MED
     , M6.HBA1C_60M, M6.HBA1C_60M_MIN, M6.HBA1C_60M_MAX, M6.HBA1C_60M_AVG --, M5.HBA1C_60M_MED
  FROM COHORT_DATA M1
  LEFT OUTER JOIN CONDITION_DATA           M2 ON M1.PERSON_ID = M2.PERSON_ID /* DKA여부, HHS여부 */
  LEFT OUTER JOIN CONDITION_DATA_DM        M3 ON M1.PERSON_ID = M3.PERSON_ID /* 제1형, 제2형 당뇨병 존재여부 */
  LEFT OUTER JOIN MEASUREMENT_DKA_DATA     M4 ON M1.PERSON_ID = M4.PERSON_ID /* DKA 검사결과값 기반 여부 */
--  LEFT OUTER JOIN PRCS_DATA1               M5 ON M1.PERSON_ID = M5.PERSON_ID /* 중앙값(MEDIAN) 데이터 */
  LEFT OUTER JOIN PRCS_DATA2               M6 ON M1.PERSON_ID = M6.PERSON_ID /* 중앙값(MEDIAN) 외 데이터 */
  LEFT OUTER JOIN CONDITION_DATA_NEW       M7 ON M1.PERSON_ID = M7.PERSON_ID /* (NEW) DKA여부, HHS여부 */
  LEFT OUTER JOIN MEASUREMENT_DKA_DATA_NEW M8 ON M1.PERSON_ID = M8.PERSON_ID /* (NEW) DKA 검사결과값 기반 여부 */
-- WHERE NVL(M4.HBA1C_00M,0)     >  NVL(M4.HBA1C_03M,0)  /* 신환환자 한정 : 0, 3개월 사이의 HbA1c가 1이상 감소한 경우 */
--   AND NVL(M4.WEIGHT_00M,0)    <  NVL(M4.WEIGHT_03M,0) /* 신환환자 한정 : 0, 3개월 사이의 Weight가 증가한 경우 */
--)
;
